### ISSUE TITLE
D-Portal previews 0 activities if you click before uploading a file

### ISSUE THREAD

**Issue by reidmporter** [NeonOpenAG/oagtoolbox#172]
If you arrive at the site and click "Preview" without uploading anything, it doesn't preview the last file, it just previews nothing - 0 activities, etc.

(Makes perfect sense but Harry said that's not what was intended)

![image](https://user-images.githubusercontent.com/15111135/32347094-f31cf08e-bfe5-11e7-8cba-876b496e4a04.png)

**Comment by harryharrold** [comment]
The *specific* report is incorrect - a new visitor to an empty instance of the site will only see the Preview link if they have uploaded a file.

*However*, if the file is not an iati compliant activities file, *then* they'll see no activities in the d-portal instance. I believe this bug will be fixed by https://github.com/NeonOpenAG/oagtoolbox/issues/147

Until then - steps to reproduce:

1) Upload a valid xml file with no activities in it.
2) Choose the "preview" link.

**Comment by tobybatch** [comment]
When an upload starts the page hangs until CoVE has finished at which point a new page is rendered.  This new page will reflect the new file as the 'active' file and that is what will be accessed at the improve/preview/download pages.
