### ISSUE TITLE
Clear old documents

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#180]
The whole system functions as a single document chain.  Clear the old documents when a new one is uploaded.

**Comment by tobybatch** [comment]
@harryharrold Do you agree?  I think the multiple documents is just confusing.

**Comment by harryharrold** [comment]
@reidmporter - for the call.

**Comment by reidmporter** [comment]
I think that makes sense, especially if we're rolling back from a docker-ized behind-the-firewall optimized model and more of a basic webpage that markets the optimized version. If there is a use case for the public site to retain documents, I'm unaware of it. HOWEVER, what happens if a user from org B logs in and sees org A's document? Does it get removed immediately after A's session closes, or does it wait until B starts their session/i.e. uploads something new? Not a big deal either way, just curious.
